### ISSUE TITLE
Not rebasing ck-hrtimer patches anymore?

### ISSUE THREAD

**Issue by graysky2** [xanmod/linux-patches#2]
I noticed that you you haven't provided a rebase to the ck-hrtimer patches since 5.15.y.  Any plans to add them back or have you dropped them totally?

I tried applying them to 5.17.1 from the 5.15.y-* directory but the last patch in the series fails.  I attempted to rebase them here.  What do you think?  The only one that required manual rebasing was `0008-clockevents-hrtimer-Make-hrtimer-granularity-and-min.patch` so please verify that I did it correctly.

https://github.com/graysky2/linux-patches/commit/de5c724ce35344cdc273cbb4114c01564abb9628

When I tried compiling it, a failure occurred:
```
  CC [M]  sound/core/control_led.o
  CC [M]  sound/core/hwdep.o
  CC      drivers/pci/pcie/pme.o
kernel/sysctl.c:1674:36: error: ‘ten_thousand’ undeclared here (not in a function)
 1674 |                 .extra2         = &ten_thousand,
      |                                    ^~~~~~~~~~~~
  CC      net/xfrm/xfrm_policy.o
make[1]: *** [scripts/Makefile.build:288: kernel/sysctl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

Complete build log: https://gist.github.com/graysky2/5574ca7610d8c8385be84b38f42f6596

**Comment by pgzh** [comment]
The build error is most likely caused by this mainline patch:

https://lore.kernel.org/all/20211221184501.574670-1-colin.i.king@gmail.com/T/#u

To restore the variable I'd leave out the preprocessor ifdefs since the printk stuff was moved out of kernel/sysctl.c, maybe like this in a patch that needs to be applied to kernel/sysctl.c before hrtimers:

 /* Constants used for minimum and  maximum */

+static const int ten_thousand = 10000;
 
 #ifdef CONFIG_PERF_EVENTS
 static const int six_hundred_forty_kb = 640 * 1024;
 #endif

It would be worth a try, but I have no idea if other problems are waiting and haven't tested this myself.
Anyways it would be nice to get the hrtimer patches working again in newer kernels.

**Comment by graysky2** [comment]
@pgzh - thanks for the reply.
@xanmod - thoughts?

**Comment by graysky2** [comment]
@pgzh - Why not just revert the patch you referenced?

**Comment by pgzh** [comment]
Because that patch was part of a patch series that moved the printk() related code out of sysctl.c .
The ten_thousand variable was not needed anymore and dropped completely.

In earlier kernel versions building a kernel with hrtimers and without printk we would have ended up with the same error.
If we keep that #define by reverting the patch, it would not be a clean solution.

So since hrtimers depends on that variable, I would rather just put it back into sysctl.c unconditionally with the hrtimer patchset and fix this (very unlikely) case as a positive side-effect.

**Comment by graysky2** [comment]
Test build was good, boots without dmesg regressions and seems to run as expected.

**Comment by graysky2** [comment]
@pgzh - reported [build failure](https://bbs.archlinux.org/viewtopic.php?pid=2031372#p2031372) using clang.  Any thoughts?

**Comment by xanmod** [comment]
We stopped supporting ck-hrtimer due to stability issues causing freezes on some hardware.

This patchset improves latency but degrades throughput.

**Comment by graysky2** [comment]
@xanmod - Can you comment on which hardware displays freezing?

**Comment by pgzh** [comment]
@xanmod The const keyword was added since Linux 5.15, so  you should try just

static int ten_thousand = 10000;

i.e. without the const keyword. Some compilers will just warn about handing over the pointer to a const variable, but clang seems to produce an error.
I've overlooked this change...

**Comment by graysky2** [comment]
Thanks, done.
